{
 "title": "API Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Tempo Médio de Resposta",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_ms_sum / http_request_duration_ms_count",
     "legendFormat": "Tempo médio de resposta (ms)"
    }
   ]
  },
  {
   "title": "Taxa de Requisições",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "Requisições por segundo" }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Requisições por Rota",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Requisições por Código de Status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (status_code)(http_requests_total)",
     "legendFormat": "Código {{status_code}}"
    }
   ]
  }
 ]
}